-- V15__add_brand_compliance_documents.sql
-- Add compliance & verification document columns to brands (tenants)

ALTER TABLE brands ADD COLUMN IF NOT EXISTS sla_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS sla_url VARCHAR(255);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS nda_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS nda_url VARCHAR(255);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS license_agreement_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS license_agreement_url VARCHAR(255);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS gst_cert_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS gst_cert_url VARCHAR(255);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS pan_aadhar_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS pan_aadhar_url VARCHAR(255);
ALTER TABLE brands ADD COLUMN IF NOT EXISTS fssai_cert_status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE brands ADD COLUMN IF NOT EXISTS fssai_cert_url VARCHAR(255);
