-- -----------------------------------------------------
-- IDENTITY DOMAIN
-- -----------------------------------------------------
CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    description varchar(255)
);

CREATE TABLE permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    description varchar(255)
);

CREATE TABLE role_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    full_name varchar(100) NOT NULL,
    phone varchar(20),
    active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- -----------------------------------------------------
-- BUSINESS DOMAIN
-- -----------------------------------------------------
CREATE TABLE brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    description varchar(255)
);

CREATE TABLE outlets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    brand_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    address varchar(255),
    phone varchar(20),
    gst_number varchar(20),
    active boolean NOT NULL DEFAULT true,
    FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE
);

CREATE TABLE terminals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    name varchar(50) NOT NULL,
    device_identifier varchar(100) NOT NULL UNIQUE,
    active boolean NOT NULL DEFAULT true,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
);

CREATE TABLE shifts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    terminal_id bigint NOT NULL,
    user_id bigint NOT NULL,
    start_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time timestamp,
    opening_balance numeric(12, 2) NOT NULL DEFAULT 0.00,
    closing_balance numeric(12, 2),
    status varchar(20) NOT NULL DEFAULT 'OPEN', -- OPEN, CLOSED
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (terminal_id) REFERENCES terminals(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- -----------------------------------------------------
-- MENU DOMAIN
-- -----------------------------------------------------
CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255),
    active boolean NOT NULL DEFAULT true,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
);

CREATE TABLE menu_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    category_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255),
    sku varchar(50) NOT NULL,
    base_price numeric(12, 2) NOT NULL DEFAULT 0.00,
    tax_rate numeric(5, 2) NOT NULL DEFAULT 0.00, -- e.g. 5.00 for 5% GST
    active boolean NOT NULL DEFAULT true,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    menu_item_id bigint NOT NULL,
    name varchar(50) NOT NULL, -- e.g. Small, Medium, Large
    price_override numeric(12, 2) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE
);

CREATE TABLE addons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    name varchar(50) NOT NULL,
    price numeric(12, 2) NOT NULL DEFAULT 0.00,
    active boolean NOT NULL DEFAULT true,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
);

CREATE TABLE recipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    menu_item_id bigint NOT NULL,
    variant_id bigint,
    name varchar(100),
    description varchar(255),
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES variants(id) ON DELETE SET NULL
);

-- -----------------------------------------------------
-- CRM DOMAIN
-- -----------------------------------------------------
CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    phone varchar(20) NOT NULL UNIQUE,
    email varchar(100),
    loyalty_points integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loyalty_wallets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL UNIQUE,
    balance_points integer NOT NULL DEFAULT 0,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    code varchar(50) NOT NULL UNIQUE,
    discount_type varchar(20) NOT NULL, -- FLAT, PERCENTAGE
    discount_value numeric(12, 2) NOT NULL,
    min_order_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    max_discount numeric(12, 2),
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE campaigns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    description varchar(255),
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL
);

CREATE TABLE customer_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL,
    address_line1 varchar(255) NOT NULL,
    address_line2 varchar(255),
    city varchar(100) NOT NULL,
    postal_code varchar(20),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- -----------------------------------------------------
-- ORDERS DOMAIN
-- -----------------------------------------------------
CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    terminal_id bigint NOT NULL,
    shift_id bigint NOT NULL,
    user_id bigint NOT NULL,
    customer_id bigint,
    order_number varchar(50) NOT NULL UNIQUE,
    order_type varchar(20) NOT NULL, -- DINE_IN, TAKEAWAY, DELIVERY
    table_number varchar(20),
    status varchar(20) NOT NULL DEFAULT 'DRAFT', -- DRAFT, PENDING, PREPARING, READY, SERVED, PAID, CANCELLED
    subtotal numeric(12, 2) NOT NULL DEFAULT 0.00,
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    tax_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    round_off numeric(5, 2) NOT NULL DEFAULT 0.00,
    total_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (terminal_id) REFERENCES terminals(id),
    FOREIGN KEY (shift_id) REFERENCES shifts(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    order_id bigint NOT NULL,
    menu_item_id bigint NOT NULL,
    variant_id bigint,
    name varchar(100) NOT NULL,
    quantity integer NOT NULL,
    price numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    tax_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    total_amount numeric(12, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (menu_item_id) REFERENCES menu_items(id),
    FOREIGN KEY (variant_id) REFERENCES variants(id) ON DELETE SET NULL
);

CREATE TABLE kot_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    order_id bigint NOT NULL,
    ticket_number varchar(50) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING', -- PENDING, PREPARING, READY, SERVED
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- -----------------------------------------------------
-- INVENTORY DOMAIN
-- -----------------------------------------------------
CREATE TABLE ingredients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    sku varchar(50) NOT NULL UNIQUE,
    unit varchar(20) NOT NULL, -- KG, LTR, PCS, GMS, MLS
    min_stock_level numeric(12, 3) NOT NULL DEFAULT 0.000,
    current_stock numeric(12, 3) NOT NULL DEFAULT 0.000,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
);

CREATE TABLE recipe_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    quantity numeric(12, 3) NOT NULL,
    unit varchar(20) NOT NULL,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE
);

CREATE TABLE vendors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    contact_name varchar(100),
    email varchar(100),
    phone varchar(20),
    address varchar(255),
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
);

CREATE TABLE purchase_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    vendor_id bigint NOT NULL,
    po_number varchar(50) NOT NULL UNIQUE,
    status varchar(20) NOT NULL DEFAULT 'DRAFT', -- DRAFT, ORDERED, RECEIVED, CANCELLED
    total_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (vendor_id) REFERENCES vendors(id)
);

CREATE TABLE purchase_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    quantity numeric(12, 3) NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    total_price numeric(12, 2) NOT NULL,
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE TABLE stock_ledger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    transaction_type varchar(50) NOT NULL, -- PURCHASE, SALE_DEDUCTION, WASTAGE, TRANSFER_IN, TRANSFER_OUT, MANUAL_ADJUST
    quantity numeric(12, 3) NOT NULL, -- positive for additions, negative for deductions
    unit_price numeric(12, 2),
    reference_id bigint, -- ID of the order, PO, wastage, etc.
    notes varchar(255),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE TABLE stock_transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    from_outlet_id bigint NOT NULL,
    to_outlet_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING', -- PENDING, COMPLETED, REJECTED
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (to_outlet_id) REFERENCES outlets(id)
);

CREATE TABLE wastage_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    quantity numeric(12, 3) NOT NULL,
    reason varchar(255),
    reported_by bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id),
    FOREIGN KEY (reported_by) REFERENCES users(id)
);

CREATE TABLE kot_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kot_ticket_id bigint NOT NULL,
    order_item_id bigint NOT NULL,
    quantity integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING', -- PENDING, PREPARING, READY, SERVED
    notes varchar(255),
    FOREIGN KEY (kot_ticket_id) REFERENCES kot_tickets(id) ON DELETE CASCADE,
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
);

CREATE TABLE discounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    order_item_id bigint,
    coupon_id bigint,
    type varchar(20) NOT NULL, -- FLAT, PERCENTAGE
    discount_value numeric(12, 2) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    reason varchar(255),
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE,
    FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE SET NULL
);

CREATE TABLE taxes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    order_item_id bigint,
    name varchar(50) NOT NULL,
    rate numeric(5, 2) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
);

-- -----------------------------------------------------
-- PAYMENTS DOMAIN
-- -----------------------------------------------------
CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    order_id bigint NOT NULL,
    amount numeric(12, 2) NOT NULL,
    payment_method varchar(50) NOT NULL, -- CASH, CARD, UPI, WALLET
    status varchar(20) NOT NULL DEFAULT 'PENDING', -- PENDING, COMPLETED, FAILED, REFUNDED
    transaction_reference varchar(100),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE payment_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE refunds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    payment_id bigint NOT NULL,
    amount numeric(12, 2) NOT NULL,
    reason varchar(255),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE settlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    shift_id bigint NOT NULL,
    payment_method varchar(50) NOT NULL,
    expected_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    actual_amount numeric(12, 2) NOT NULL DEFAULT 0.00,
    discrepancy numeric(12, 2) NOT NULL DEFAULT 0.00,
    notes varchar(255),
    FOREIGN KEY (shift_id) REFERENCES shifts(id)
);

-- -----------------------------------------------------
-- REPORTING DOMAIN
-- -----------------------------------------------------
CREATE TABLE report_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    report_type varchar(50) NOT NULL,
    snapshot_date timestamp NOT NULL,
    data_json text NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id)
);

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_id bigint,
    user_id bigint,
    action varchar(255) NOT NULL,
    entity_name varchar(100) NOT NULL,
    entity_id bigint,
    old_value text,
    new_value text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE integration_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name varchar(100) NOT NULL,
    direction varchar(20) NOT NULL, -- INBOUND, OUTBOUND
    payload text,
    status varchar(20) NOT NULL, -- SUCCESS, FAILED, RETRYING
    error_message text,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
