-- Create Dining Floors/Areas Table
CREATE TABLE dining_floors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    active boolean NOT NULL DEFAULT true
);

-- Create Dining Tables Table
CREATE TABLE dining_tables (
    id varchar(50) PRIMARY KEY, -- e.g. 'T1', 'T2'
    seats integer NOT NULL DEFAULT 4,
    status varchar(30) NOT NULL DEFAULT 'Available', -- Available, Occupied, Reserved, Billing, Cleaning, OutOfService
    merged_into varchar(50), -- Reference to parent table if merged
    floor_id bigint NOT NULL,
    active_order_id bigint, -- Tracks current active order if occupied/billing
    waiter_name varchar(100),
    customer_name varchar(100),
    customer_phone varchar(20),
    reservation_time timestamp,
    FOREIGN KEY (floor_id) REFERENCES dining_floors(id) ON DELETE CASCADE,
    FOREIGN KEY (merged_into) REFERENCES dining_tables(id) ON DELETE SET NULL
);

-- Seed Initial Floors & Tables
INSERT INTO dining_floors (name) VALUES ('Ground Floor'), ('First Floor'), ('Terrace'), ('VIP Cabin');

-- Seed Ground Floor (T1 to T6)
INSERT INTO dining_tables (id, seats, status, floor_id) VALUES 
('T1', 2, 'Available', 1),
('T2', 4, 'Available', 1),
('T3', 4, 'Available', 1),
('T4', 6, 'Available', 1),
('T5', 2, 'Available', 1),
('T6', 4, 'Available', 1);

-- Seed First Floor (T7 to T14)
INSERT INTO dining_tables (id, seats, status, floor_id) VALUES 
('T7', 8, 'Available', 2),
('T8', 4, 'Available', 2),
('T9', 4, 'Available', 2),
('T10', 6, 'Available', 2),
('T11', 2, 'Available', 2),
('T12', 4, 'Available', 2),
('T13', 4, 'Available', 2),
('T14', 6, 'Available', 2);

-- Seed Terrace (T15 to T20)
INSERT INTO dining_tables (id, seats, status, floor_id) VALUES 
('T15', 8, 'Available', 3),
('T16', 2, 'Available', 3),
('T17', 4, 'Available', 3),
('T18', 4, 'Available', 3),
('T19', 6, 'Available', 3),
('T20', 4, 'Available', 3);

-- Seed VIP Cabin (V1, V2)
INSERT INTO dining_tables (id, seats, status, floor_id) VALUES 
('V1', 4, 'Available', 4),
('V2', 6, 'Available', 4);
