-- 1. Create Subscription Plans
CREATE TABLE subscription_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    max_users integer NOT NULL,
    max_branches integer NOT NULL,
    max_products integer NOT NULL,
    max_tables integer NOT NULL,
    max_kitchens integer NOT NULL,
    max_printers integer NOT NULL,
    storage_limit_gb numeric(10, 2) NOT NULL,
    monthly_price numeric(10, 2) NOT NULL,
    yearly_price numeric(10, 2) NOT NULL,
    trial_days integer NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- Seed Default Subscription Plans
INSERT INTO subscription_plans (name, max_users, max_branches, max_products, max_tables, max_kitchens, max_printers, storage_limit_gb, monthly_price, yearly_price, trial_days) VALUES
('Basic', 5, 1, 100, 10, 1, 1, 2.00, 999.00, 9999.00, 14),
('Standard', 15, 3, 500, 30, 2, 2, 10.00, 1999.00, 19999.00, 14),
('Professional', 50, 10, 2000, 100, 5, 5, 50.00, 4999.00, 49999.00, 14),
('Enterprise', 9999, 9999, 99999, 9999, 99, 99, 500.00, 9999.00, 99999.00, 14),
('Custom', 99999, 99999, 999999, 99999, 999, 999, 9999.00, 0.00, 0.00, 14);

-- 2. Alter Brands to Add Tenant/Owner Details
ALTER TABLE brands ADD COLUMN owner_name varchar(100) DEFAULT 'Resto Owner';
ALTER TABLE brands ADD COLUMN owner_email varchar(100) DEFAULT 'owner@resto360.com';
ALTER TABLE brands ADD COLUMN owner_mobile varchar(20) DEFAULT '9876543210';
ALTER TABLE brands ADD COLUMN gst_number varchar(20) DEFAULT 'GST123456789';
ALTER TABLE brands ADD COLUMN address text DEFAULT '123 Main Street';
ALTER TABLE brands ADD COLUMN subscription_plan_id bigint REFERENCES subscription_plans(id) DEFAULT 1;
ALTER TABLE brands ADD COLUMN status varchar(20) DEFAULT 'ACTIVE'; -- ACTIVE, INACTIVE, SUSPENDED
ALTER TABLE brands ADD COLUMN trial_expires_at timestamp DEFAULT CURRENT_TIMESTAMP + INTERVAL '14 days';
ALTER TABLE brands ADD COLUMN expires_at timestamp DEFAULT CURRENT_TIMESTAMP + INTERVAL '30 days';
ALTER TABLE brands ADD COLUMN currency varchar(10) DEFAULT 'INR';
ALTER TABLE brands ADD COLUMN timezone varchar(50) DEFAULT 'Asia/Kolkata';
ALTER TABLE brands ADD COLUMN logo_url varchar(255);
ALTER TABLE brands ADD COLUMN created_at timestamp DEFAULT CURRENT_TIMESTAMP;

-- 3. Create SaaS Supporting Tables
CREATE TABLE licenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    license_key varchar(255) NOT NULL UNIQUE,
    type varchar(20) NOT NULL, -- CLOUD, OFFLINE, DESKTOP
    status varchar(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, DEACTIVATED, EXPIRED
    activated_at timestamp,
    expires_at timestamp NOT NULL
);

CREATE TABLE feature_toggles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    module_key varchar(50) NOT NULL, -- POS, KITCHEN_DISPLAY, CRM, INVENTORY, QR_ORDERING, etc.
    enabled boolean NOT NULL DEFAULT true,
    UNIQUE(tenant_id, module_key)
);

CREATE TABLE saas_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE,
    username varchar(100) NOT NULL,
    action varchar(255) NOT NULL,
    ip_address varchar(45),
    device_details varchar(255),
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- Seed feature toggles for existing brands
INSERT INTO feature_toggles (tenant_id, module_key, enabled)
SELECT b.id, m.key, true
FROM brands b
CROSS JOIN (
    VALUES 
    ('POS'), ('KITCHEN_DISPLAY'), ('CRM'), ('INVENTORY'), 
    ('REPORTS'), ('ANALYTICS'), ('WHATSAPP'), ('SMS'), 
    ('TABLE_RESERVATION'), ('QR_ORDERING'), ('ONLINE_ORDERS'),
    ('LOYALTY_PROGRAM'), ('COUPONS'), ('AI_REPORTS'), ('RECIPE_MANAGEMENT')
) AS m(key);

-- 4. Add tenant_id Column to Data Tables
ALTER TABLE outlets ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE users ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE dining_floors ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE dining_tables ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE categories ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE menu_items ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE orders ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;
ALTER TABLE kot_tickets ADD COLUMN tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE;

-- Populate existing rows
UPDATE outlets SET tenant_id = brand_id;
UPDATE users SET tenant_id = 1; -- Default brand
UPDATE dining_floors SET tenant_id = 1;
UPDATE dining_tables SET tenant_id = 1;
UPDATE categories SET tenant_id = (SELECT tenant_id FROM outlets WHERE outlets.id = categories.outlet_id);
UPDATE menu_items SET tenant_id = (SELECT tenant_id FROM categories WHERE categories.id = menu_items.category_id);
UPDATE orders SET tenant_id = (SELECT tenant_id FROM outlets WHERE outlets.id = orders.outlet_id);
UPDATE kot_tickets SET tenant_id = (SELECT tenant_id FROM outlets WHERE outlets.id = kot_tickets.outlet_id);

-- Enforce NOT NULL for future rows
ALTER TABLE outlets ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE users ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE dining_floors ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE dining_tables ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE categories ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE menu_items ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE kot_tickets ALTER COLUMN tenant_id SET NOT NULL;

-- 5. Enable Row-Level Security (RLS) on PostgreSQL
ALTER TABLE outlets ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE dining_floors ENABLE ROW LEVEL SECURITY;
ALTER TABLE dining_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE kot_tickets ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
CREATE POLICY outlets_rls ON outlets FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY users_rls ON users FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY dining_floors_rls ON dining_floors FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY dining_tables_rls ON dining_tables FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY categories_rls ON categories FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY menu_items_rls ON menu_items FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY orders_rls ON orders FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);
CREATE POLICY kot_tickets_rls ON kot_tickets FOR ALL USING (tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::bigint);

-- Create Indexes for optimization
CREATE INDEX idx_outlets_tenant ON outlets(tenant_id);
CREATE INDEX idx_users_tenant ON users(tenant_id);
CREATE INDEX idx_dining_floors_tenant ON dining_floors(tenant_id);
CREATE INDEX idx_dining_tables_tenant ON dining_tables(tenant_id);
CREATE INDEX idx_categories_tenant ON categories(tenant_id);
CREATE INDEX idx_menu_items_tenant ON menu_items(tenant_id);
CREATE INDEX idx_orders_tenant ON orders(tenant_id);
CREATE INDEX idx_kot_tickets_tenant ON kot_tickets(tenant_id);
