-- V6: SaaS enhancements schema migration

-- Add status and control fields to brands
ALTER TABLE brands ADD COLUMN IF NOT EXISTS locked boolean NOT NULL DEFAULT false;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS archived boolean NOT NULL DEFAULT false;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS suspended_at timestamp DEFAULT NULL;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS suspended_reason varchar(255) DEFAULT NULL;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS storage_used_mb numeric(12, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE brands ADD COLUMN IF NOT EXISTS last_activity_at timestamp DEFAULT NULL;

-- Add features_json to subscription_plans
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS features_json text DEFAULT NULL;

-- Add details to saas_audit_logs
ALTER TABLE saas_audit_logs ADD COLUMN IF NOT EXISTS old_value text DEFAULT NULL;
ALTER TABLE saas_audit_logs ADD COLUMN IF NOT EXISTS new_value text DEFAULT NULL;
ALTER TABLE saas_audit_logs ADD COLUMN IF NOT EXISTS module varchar(100) DEFAULT NULL;

-- Add security controls to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS force_password_change boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_disabled boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at timestamp DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_attempt_count integer NOT NULL DEFAULT 0;

-- 1. login_history
CREATE TABLE IF NOT EXISTS login_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE,
    username varchar(100) NOT NULL,
    login_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address varchar(45) DEFAULT NULL,
    device_details varchar(255) DEFAULT NULL,
    status varchar(20) NOT NULL -- SUCCESS, FAILED
);

-- 2. password_history
CREATE TABLE IF NOT EXISTS password_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    password_hash varchar(255) NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. device_sessions
CREATE TABLE IF NOT EXISTS device_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    device_token varchar(255) NOT NULL UNIQUE,
    device_name varchar(255) DEFAULT NULL,
    active boolean NOT NULL DEFAULT true,
    last_accessed timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 4. notifications
CREATE TABLE IF NOT EXISTS notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint REFERENCES brands(id) ON DELETE CASCADE,
    message varchar(255) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    type varchar(50) NOT NULL, -- EXPIRY, SYSTEM, LICENSE
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. impersonation_logs
CREATE TABLE IF NOT EXISTS impersonation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    impersonator_username varchar(100) NOT NULL,
    impersonated_username varchar(100) NOT NULL,
    impersonated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address varchar(45) DEFAULT NULL
);
