CREATE TABLE ingredient_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL UNIQUE,
    outlet_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    FOREIGN KEY (outlet_id) REFERENCES outlets(id) ON DELETE CASCADE
);

INSERT INTO ingredient_categories (uuid, outlet_id, name) VALUES
('b19616e2-e1ea-42f5-b661-d70377a0601a', 1, 'Vegetables'),
('e31a89c8-d14c-47ea-8316-b81622b392a1', 1, 'Dairy'),
('20ab88e1-512b-4d43-9822-262aa22b3c22', 1, 'Meat'),
('50ab88e2-612b-5d43-a822-362aa32b3c23', 1, 'Grains'),
('90ab88e3-712b-6d43-b822-462aa42b3c24', 1, 'Spices'),
('c0ab88e4-812b-7d43-c822-562aa52b3c25', 1, 'General');

SELECT setval(pg_get_serial_sequence('ingredient_categories', 'id'), COALESCE(max(id), 1)) FROM ingredient_categories;
